branch-defaults:
  default:
    environment: image-filter092022-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  image-filter092022-dev:
    branch: null
    repository: null
global:
  application_name: image-filter 092022
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
